package com.example.coursework2_20210557.database

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "MealData")
data class MealData(
    @PrimaryKey(autoGenerate = false)
    val idMeal: String,
    val strMeal: String,
    val strDrinkAlternate: String?,
    val strCategory: String?,
    val strArea: String?,
    val strInstructions: String?,
    val strMealThumb: String?,
    val strTags: String?,
    val strYoutube: String?,
    val strIngredient01: String?,
    val strIngredient02: String?,
    val strIngredient03: String?,
    val strIngredient04: String?,
    val strIngredient05: String?,
    val strIngredient06: String?,
    val strIngredient07: String?,
    val strIngredient08: String?,
    val strIngredient09: String?,
    val strIngredient10: String?,
    val strIngredient11: String?,
    val strIngredient12: String?,
    val strIngredient13: String?,
    val strIngredient14: String?,
    val strIngredient15: String?,
    val strIngredient16: String?,
    val strIngredient17: String?,
    val strIngredient18: String?,
    val strIngredient19: String?,
    val strIngredient20: String?,
    val strMeasures01: String?,
    val strMeasures02: String?,
    val strMeasures03: String?,
    val strMeasures04: String?,
    val strMeasures05: String?,
    val strMeasures06: String?,
    val strMeasures07: String?,
    val strMeasures08: String?,
    val strMeasures09: String?,
    val strMeasures10: String?,
    val strMeasures11: String?,
    val strMeasures12: String?,
    val strMeasures13: String?,
    val strMeasures14: String?,
    val strMeasures15: String?,
    val strMeasures16: String?,
    val strMeasures17: String?,
    val strMeasures18: String?,
    val strMeasures19: String?,
    val strMeasures20: String?,
    val strSource: String?,
    val strImageSource: String?,
    val strCreativeCommonsConfirmed: String?,
    val strDateModified: String?,
)
